### PR TITLE
Add entry_points as py_binary's

### PR DESCRIPTION
**Pull request by fahhem**
This auto-generates every entry_point as a py_binary (by relying on the generated console_script's created by pip)

### CODE REVIEW

**Comment by fahhem** [comment]
I added a test as well, and checked that it doesn't work without the rest of this change

**Comment by ali5h** [comment]
really nice, this was a long time todo

**Comment by fahhem** [comment]
Can you mark a new release soon? Not a big deal, but would be nice to refer to a release version rather than a commit on master :D

**Comment by ali5h** [comment]
i like commits really, i invited you as a collaborator, r u interested?

**Comment by fahhem** [comment]
yes, thank you! I'll still send PR's and such so I don't break master at least without a review :)

**Pull request merged**
