### PR TITLE
Py-compile-3.7: change args per issue 811

### PR DESCRIPTION
**Pull request by chickenandpork**
As discussed in https://github.com/jazzband/pip-tools/issues/811 with a quick change at https://github.com/jazzband/pip-tools/issues/811#issuecomment-1058233070, py-compile-3.7.0 no longer accepts `--no-index`, fairly suddenly as well.

The `--no-emit-index-url` is a replacement.

Probably need to discuss how to properly and gracefully maintain compatibility: probably need to make it check the version of the interpreter, or allow user-setting.

### CODE REVIEW

**Comment by ali5h** [comment]
please rebase on master, thanks

**Comment by chickenandpork** [comment]
@ali5h rebased

**Comment by ali5h** [comment]
I don't fully understand your concern. what do you mean user provides the pip-tools?

**Comment by fahhem** [comment]
piptools (in which pip-compile is from) is vendored into the repo under third_party to solve the chicken-or-egg problem of getting rules_pip's dependencies via pip. As a result, our version of pip-compile will always be 6.4.0: https://github.com/ali5h/rules_pip/tree/master/third_party/py/pip_tools-6.4.0.dist-info

Can you verify that the issue a) is in 6.4.0, b) is solved by your change, and c) there is a test that compiles the requirements.txt?

I haven't 100% checked, but it seems to me that this isn't an issue since the generated `requirements.txt` isn't checked into user repositories, only kept in cache by bazel so the index URL being in the output doesn't matter. Is that the case?

**Pull request closed without merging**
